plugins {
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = rootProject.neoform_version

    parchment {
        minecraftVersion = rootProject.parchment_minecraft_version
        mappingsVersion = rootProject.parchment_mappings_version
    }
}

dependencies {
    compileOnly "org.spongepowered:mixin:0.8.7"
    compileOnly "com.google.code.findbugs:jsr305:3.0.2"
}
