modLoader = "javafml"
loaderVersion = "[1,)"
license = "Apache-2.0"

[[mods]]
modId = "betterbeacons"
version = "${version}"
displayName = "Better Beacons"
authors = "Monte_Carlo_Simulations"
logoFile = "icon.png"
description = '''
A standalone overhaul for the Minecraft beacon system.
'''

[[dependencies.betterbeacons]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.betterbeacons]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "betterbeacons.mixins.json"
